### ISSUE TITLE
Create scala defined artifact versions (2.12)

### ISSUE THREAD

**Issue by scooterGrun** [ozwolf-software/dropwizard-raml#5]
Can you please create scala specific artifacts for this library (especially for 2.12)?

Newer libraries (such as kafka-clients:2.4) seem to be using 2.12 as standard now, and this library uses a scala dependency (com.kjetland/mbknor-jackson-jsonschema) but doesn't generate the corresponding artifacts.

**Comment by OzWolf** [comment]
Fixed by PR 6.
